config/routes.rb
# frozen_string_literal: true


Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}

  root to: "home#index"

  resources :tasks

  resources :categories

  resources :tags
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks, dependent: :nullify
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :task_tags
    has_many :tasks, through: :task_tags
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags
  has_many :comments, dependent: :destroy
end

app/models/task_tag.rb
class TaskTag < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :tasks
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def after_sign_in_path_for(resource)
      tasks_path(current_user.id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
      @categories = Category.all
    end
  
    def show
    end
  
    def new
      @category = Category.new
    end
  
    def edit
    end
  
    def create
      @category = Category.new(category_params)
  
      if @category.save
        redirect_to @category, notice: 'Категория успешно создана.'
      else
        render :new
      end
    end
  
    def update
      if @category.update(category_params)
        redirect_to @category, notice: 'Категория успешно обновлена.'
      else
        render :edit
      end
    end
  
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Категория успешно удалена.'
    end
  
    private
      def set_category
        @category = Category.find(params[:id])
      end
  
      def category_params
        params.require(:category).permit(:name)
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_task

  def new
    @comment = @task.comments.build
  end
  
  def edit
    @comment = @task.comments.find(params[:id])
  end
  
  def create
    @comment = @task.comments.build(comment_params)
    @comment.user_id = @task.user_id  # Устанавливаем user_id комментария равным user_id задачи
    if @comment.save
      redirect_to @task, notice: 'Комментарий успешно добавлен.'
    else
      render 'tasks/show'
    end
  end

  def update
    @comment = @task.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @task, notice: 'Комментарий успешно обновлен.'
    else
      render 'tasks/show'
    end
  end
  def destroy
   
    @comment = @task.comments.find(params[:id])
    @comment.destroy
    redirect_to @task, notice: 'Комментарий успешно удален.'
  end

  def show
    @comment = @task.comments.find(params[:id])
  end
  
  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end


  
  

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        render 
    end

    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :set_tag, only: [:show, :edit, :update, :destroy]
  
    # GET /tags
    def index
      @tags = Tag.all
    end
  
    # GET /tags/1
    def show
    end
  
    # GET /tags/new
    def new
      @tag = Tag.new
    end
  
    # GET /tags/1/edit
    def edit
    end
  
    # POST /tags
    def create
      @tag = Tag.new(tag_params)
  
      if @tag.save
        redirect_to @tag, notice: 'Tag was successfully created.'
      else
        render :new
      end
    end
  
    # PATCH/PUT /tags/1
    def update
      if @tag.update(tag_params)
        redirect_to @tag, notice: 'Tag was successfully updated.'
      else
        render :edit
      end
    end
  
    # DELETE /tags/1
    def destroy
      @tag.destroy
      redirect_to tags_url, notice: 'Tag was successfully destroyed.'
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_tag
        @tag = Tag.find(params[:id])
      end
  
      # Only allow a trusted parameter "white list" through.
      def tag_params
        params.require(:tag).permit(:name)
      end
  end
  

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
# POST /tasks
def create
  @task = current_user.tasks.build(task_params)
  tag_names = params[:task][:tag_names].split(',')

  tag_names.each do |tag_name|
    @tag = Tag.find_or_create_by(name: tag_name.strip)
    @task.tags << @tag
  end

  if @task.save
    redirect_to @task, notice: 'Task was successfully created.'
  else
    render :new
  end
end


  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def task_params
      params.require(:task).permit(:title, :description, :category_id)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class="item mb-sm">
  <h2 class="item-title"><%= category.name %></h2>
</div>

<div class="item-footer text-sm">
    <div class="item-date text-grey"></div>
    <div class="item-actions">
      <%= link_to fa_icon("pencil"), edit_category_path(category),
        title: 'изменить категорию', class: 'edit-item'%>
      <%= button_to fa_icon("trash-o"), category_path(category),
        method: :delete, title: 'удалить категорию', class: 'delete-item'%>
    </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
    <p><%= form.label :name, "Название категории" %></p>
    <p><%= form.text_field :name, class: 'form-text-field' %></p>
  
    <p class="mt"><%= form.submit 'Сохранить категорию', class: 'button button-main'%></p>
  <% end %>

app/views/categories/edit.html.erb
<div class="container">
    <h2 class="title-lg mb">Редактирование категории: <%= @category.id %></h2>

    <%= render 'form', category: @category %>
    
    <p class="mt"><%= link_to "Все категории", categories_path %></p>
</div>

app/views/categories/index.html.erb
<div class="container mt-sm">
  <h2 class="title-lg ">Все категории:</h2>
</div>

<% @categories.each do |category| %>
    <div class="mt-sm container">
    <%= render category %> 
    </div>
<% end %>

<div class="container">
    <p class="mt">
      <%= link_to "Создать новую категорию", new_category_path, class: 'button button-main' %>
    </p>
</div>

app/views/categories/new.html.erb
<div class="container">
    <h2 class="title-lg mb">Новая категория:</h2>

    <%= render 'form', category: @category %>

    <p class="mt"><%= link_to "Все категории", categories_path %></p>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Категория: <%= @category.id %></h2>

  <%= render 'category', category: @category %>

  <p class="mt"><%= link_to "Все категории", categories_path %></p>
</div>

app/views/comments/_form.html.erb
<%= form_with model: comment do |form| %>
    <p><%= form.text_field :content, class: 'form-text-field' %></p>
  
    <p class="mt"><%= form.submit 'Сохранить комментарий', class: 'button button-main'%></p>
  <% end %>

app/views/comments/edit.html.erb
<h1>Редактировать комментарий</h1>

<%= form_for [@task, @comment] do |f| %>
  <p>
    <%= f.label :content, "Содержание" %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit "Обновить комментарий" %>
  </p>
<% end %>

<%= link_to 'Назад', task_path(@task) %>

app/views/comments/new.html.erb
<div class="container">
    <h2 class="title-lg mb">Новый коментарий</h2>

    <%= render 'form', comment: @comment %>

    <p class="mt"><%= link_to "вернуться к задаче", task_path %></p>
</div>

app/views/comments/show.html.erb
<div class="container">
  <h2 class="title-lg mb">коментарий: <%= @comment.id %></h2>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %> 
      <%= button_to "Выйти", destroy_user_session_path, method: :delete %> 
  <% else %>
      <%= button_to "Войти", new_user_session_path %> 
  <% end %>

  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/_form.html.erb
<%= form_with model: tag do |form| %>
    <p><%= form.label :name, "Название тега" %></p>
    <p><%= form.text_field :name, class: 'form-text-field' %></p>
  
    <p class="mt"><%= form.submit 'Сохранить тег', class: 'button button-main'%></p>
  <% end %>

app/views/tags/_tag.html.erb
<div class="item mb-sm">
  <h2 class="item-title"><%= tag.name %></h2>
</div>

<div class="item-footer text-sm">
    <div class="item-date"></div>

    <div class="item-actions">
      <%= link_to fa_icon("pencil"), edit_tag_path(tag),
        title: 'изменить тег', class: 'edit-item'%>
      <%= button_to fa_icon("trash-o"), tag_path(tag),
        method: :delete, title: 'удалить тег', class: 'delete-item'%>
    </div>
</div>

app/views/tags/edit.html.erb
<div class="container">
    <h2 class="title-lg mb">Редактирование тега: <%= @tag.id %></h2>

    <%= render 'form', tag: @tag %>

    <p class="mt"><%= link_to "Все теги", tags_path %></p>
</div>

app/views/tags/index.html.erb
<div class="container mt-sm">
  <h2 class="title-lg ">Все теги:</h2>
</div>

  <% @tags.each do |tag| %>
    <div class="mt-sm container">
    <%= render tag %> 
    </div>
<% end %>

<div class="container">
    <p class="mt">
      <%= link_to "Создать новый тег", new_tag_path, class: 'button button-main' %>
    </p>
</div>

app/views/tags/new.html.erb
<div class="container">
    <h2 class="title-lg mb">Новый тег</h2>

    <%= render 'form', tag: @tag %>

    <p class="mt"><%= link_to "Все теги", tags_path %></p>
</div>

app/views/tags/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Тег: <%= @tag.id %></h2>

  <%= render 'tag', tag: @tag %>

  <p class="mt"><%= link_to "Все теги", tags_path %></p>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: task do |form| %>
  <p><%= form.label :title, "Название задачи" %></p>
  <p><%= form.text_field :title, class: 'form-text-field' %></p>

  <p><%= form.label :description, "Описание задачи" %></p>
  <p><%= form.text_area :description, rows: 5, class: 'form-text-area' %></p>

  <p class="mt"><%= form.label :category_id, "Категория" %></p>
  <p><%= form.collection_select :category_id, Category.all, :id, :name, {}, {class: 'form-select-field'} %></p>

  <p class="mt"><%= form.label :tag_names, "Добавить теги" %></p>
  <p><%= form.text_field :tag_names, class: 'form-text-field' %></p>

  <p class="mt"><%= form.submit 'Сохранить задачу', class: 'button button-main'%></p>
<% end %>

app/views/tasks/_task.html.erb
<div class="yellow-cell" style="border: 1px solid black; padding: 10px;">
  <h2 class="item-title"><%= task.title %></h2>
  <p class="item-description"><%= task.description %></p>
</div>

<div class="item-footer text-sm" style="border: 1px solid black; padding: 10px;">
    <div class="item-date text-grey">
      <%= l(task.created_at, format: :short) %>
      <% if task.category.present? %>
      <p class="item-category"><%= task.category.name %></p>
    <% end %>
    <% if task.tags.present? %>
      <p>Tags: <%= task.tags.map(&:name).join(' ') %></p>
    <% end %>
    </div>

    <div class="item-actions">
      <%= link_to fa_icon("pencil"), edit_task_path(task),
        title: 'изменить вопрос', class: 'edit-item'%>
      <%= button_to fa_icon("trash-o"), task_path(task),
        method: :delete, title: 'удалить вопрос', class: 'delete-item'%>
    </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
    <h2 class="title-lg mb">Редактирование задачи: <%= @task.id %></h2>

    <%= render 'form', task: @task %>

    <p class="mt"><%= link_to "Все задачи", tasks_path %></p>
</div>

app/views/tasks/index.html.erb
<div class="container mt-sm">
  <h2 class="title-lg ">Все задачи:</h2>
    <div class="mt-sm" style="display: flex; align-items: center;">
      <p style="margin-right: 10px;">Категории:</p>
      <%= select_tag "category", options_from_collection_for_select(Category.all, "id", "name") %>
    </div>
</div>

  <% @tasks.each do |task| %>
    <div class="mt-sm container">
    <%= render task %> 
    </div>
  <% end %>

<div class="container">
    <p class="mt">
      <%= link_to "Создать новую задачу", new_task_path, class: 'button button-main' %>
    </p>
</div>

app/views/tasks/new.html.erb
<div class="container">
    <h2 class="title-lg mb">Новая задача:</h2>

    <%= render 'form', task: @task %>

    <p class="mt"><%= link_to "Все задачи", tasks_path %></p>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Задача: <%= @task.id %></h2>

  <%= render 'task', task: @task %>

  <p class="mt"><%= link_to "Все задачи", tasks_path %></p>
</div>